const dummyProfiles: ProfileModel[] = [
  {
    id: 1,
    name: "John Doe",
    nickname: "CodeMaster42",
    position: "Software Engineer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: true, // 유일한 소유자
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2023-09-20"),
    email: "john.doe@example.com",
    workspaceId: 1,
    memberId: 1,
  },
  {
    id: 2,
    name: "Jane Smith",
    nickname: "PixelQueen99",
    position: "Product Manager",
    status: "In a meeting",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-02-20"),
    updatedAt: new Date("2023-09-21"),
    email: "jane.smith@example.com",
    workspaceId: 1,
    memberId: 2,
  },
  {
    id: 3,
    name: "Mike Johnson",
    nickname: "DesignWizard007",
    position: "UI/UX Designer",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2023-03-10"),
    updatedAt: new Date("2023-09-22"),
    email: "mike.johnson@example.com",
    workspaceId: 1,
    memberId: 3,
  },
  {
    id: 4,
    name: "Emily Brown",
    nickname: "DataNinja2023",
    position: "Data Analyst",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-04-05"),
    updatedAt: new Date("2023-09-23"),
    email: "emily.brown@example.com",
    workspaceId: 1,
    memberId: 4,
  },
  {
    id: 5,
    name: "Chris Lee",
    nickname: "CloudMaster365",
    position: "DevOps Engineer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-05-12"),
    updatedAt: new Date("2023-09-24"),
    email: "chris.lee@example.com",
    workspaceId: 1,
    memberId: 5,
  },
  {
    id: 6,
    name: "Sarah Wilson",
    nickname: "ContentGuru101",
    position: "Marketing Specialist",
    status: "In a call",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-06-18"),
    updatedAt: new Date("2023-09-25"),
    email: "sarah.wilson@example.com",
    workspaceId: 1,
    memberId: 6,
  },
  {
    id: 7,
    name: "David Kim",
    nickname: "FrontEndPro88",
    position: "Frontend Developer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2023-07-22"),
    updatedAt: new Date("2023-09-26"),
    email: "david.kim@example.com",
    workspaceId: 1,
    memberId: 7,
  },
  {
    id: 8,
    name: "Lisa Chen",
    nickname: "ServerSide123",
    position: "Backend Developer",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-08-30"),
    updatedAt: new Date("2023-09-27"),
    email: "lisa.chen@example.com",
    workspaceId: 1,
    memberId: 8,
  },
  {
    id: 9,
    name: "Tom Jackson",
    nickname: "BugHunter404",
    position: "QA Engineer",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-09-05"),
    updatedAt: new Date("2023-09-28"),
    email: "tom.jackson@example.com",
    workspaceId: 1,
    memberId: 9,
  },
  {
    id: 10,
    name: "Emma Davis",
    nickname: "ProjectMaster2000",
    position: "Project Manager",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2023-10-10"),
    updatedAt: new Date("2023-10-10"),
    email: "emma.davis@example.com",
    workspaceId: 1,
    memberId: 10,
  },
  {
    id: 11,
    name: "Alex Turner",
    nickname: "DataWizard42",
    position: "Data Scientist",
    status: "In a meeting",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-11-15"),
    updatedAt: new Date("2023-11-15"),
    email: "alex.turner@example.com",
    workspaceId: 1,
    memberId: 11,
  },
  {
    id: 12,
    name: "Olivia White",
    nickname: "UXMindReader99",
    position: "UX Researcher",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2023-12-20"),
    updatedAt: new Date("2023-12-20"),
    email: "olivia.white@example.com",
    workspaceId: 1,
    memberId: 12,
  },
  {
    id: 13,
    name: "Ryan Miller",
    nickname: "SysGuru777",
    position: "Systems Analyst",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
    email: "ryan.miller@example.com",
    workspaceId: 1,
    memberId: 13,
  },
  {
    id: 14,
    name: "Sophie Taylor",
    nickname: "WordSmith2024",
    position: "Content Writer",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    email: "sophie.taylor@example.com",
    workspaceId: 1,
    memberId: 14,
  },
  {
    id: 15,
    name: "Daniel Park",
    nickname: "MobileDevGuru",
    position: "Mobile Developer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
    email: "daniel.park@example.com",
    workspaceId: 1,
    memberId: 15,
  },
  {
    id: 16,
    name: "Ava Robinson",
    nickname: "PeopleFirst23",
    position: "HR Manager",
    status: "In a call",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-04-10"),
    email: "ava.robinson@example.com",
    workspaceId: 1,
    memberId: 16,
  },
  {
    id: 17,
    name: "Ethan Cooper",
    nickname: "SalesWizard101",
    position: "Sales Representative",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-05-15"),
    email: "ethan.cooper@example.com",
    workspaceId: 1,
    memberId: 17,
  },
  {
    id: 18,
    name: "Mia Garcia",
    nickname: "PixelPerfect2022",
    position: "Graphic Designer",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-06-20"),
    updatedAt: new Date("2024-06-20"),
    email: "mia.garcia@example.com",
    workspaceId: 1,
    memberId: 18,
  },
  {
    id: 19,
    name: "Lucas Wright",
    nickname: "HelpDesk24x7",
    position: "Customer Support",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2024-07-25"),
    updatedAt: new Date("2024-07-25"),
    email: "lucas.wright@example.com",
    workspaceId: 1,
    memberId: 19,
  },
  {
    id: 20,
    name: "Isabella Lopez",
    nickname: "FinanceGuru365",
    position: "Financial Analyst",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-08-30"),
    updatedAt: new Date("2024-08-30"),
    email: "isabella.lopez@example.com",
    workspaceId: 1,
    memberId: 20,
  },
  {
    id: 21,
    name: "Noah Adams",
    nickname: "AIExplorer2025",
    position: "AI Researcher",
    status: "In a meeting",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-09-05"),
    updatedAt: new Date("2024-09-05"),
    email: "noah.adams@example.com",
    workspaceId: 1,
    memberId: 21,
  },
  {
    id: 22,
    name: "Zoe Baker",
    nickname: "CyberDefender01",
    position: "Cybersecurity Analyst",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2024-10-10"),
    updatedAt: new Date("2024-10-10"),
    email: "zoe.baker@example.com",
    workspaceId: 1,
    memberId: 22,
  },
  {
    id: 23,
    name: "Liam Carter",
    nickname: "CloudArchitect99",
    position: "Cloud Architect",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
    email: "liam.carter@example.com",
    workspaceId: 1,
    memberId: 23,
  },
  {
    id: 24,
    name: "Aria Diaz",
    nickname: "BlockchainPioneer",
    position: "Blockchain Developer",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-20"),
    email: "aria.diaz@example.com",
    workspaceId: 1,
    memberId: 24,
  },
  {
    id: 25,
    name: "Owen Evans",
    nickname: "VRMaster3000",
    position: "VR Developer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2025-01-25"),
    updatedAt: new Date("2025-01-25"),
    email: "owen.evans@example.com",
    workspaceId: 1,
    memberId: 25,
  },
  {
    id: 26,
    name: "Chloe Foster",
    nickname: "SEOGuru2023",
    position: "SEO Specialist",
    status: "In a call",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2025-02-28"),
    updatedAt: new Date("2025-02-28"),
    email: "chloe.foster@example.com",
    workspaceId: 1,
    memberId: 26,
  },
  {
    id: 27,
    name: "Mason Gray",
    nickname: "IoTInnovator42",
    position: "IoT Engineer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2025-03-30"),
    updatedAt: new Date("2025-03-30"),
    email: "mason.gray@example.com",
    workspaceId: 1,
    memberId: 27,
  },
  {
    id: 28,
    name: "Sophia Hayes",
    nickname: "AIEthicist101",
    position: "AI Ethics Researcher",
    status: "Away",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: false,
    isOwner: false,
    createdAt: new Date("2025-04-15"),
    updatedAt: new Date("2025-04-15"),
    email: "sophia.hayes@example.com",
    workspaceId: 1,
    memberId: 28,
  },
  {
    id: 29,
    name: "Leo Ingram",
    nickname: "QuantumCoder2025",
    position: "Quantum Computing Researcher",
    status: "Do not disturb",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-05-20"),
    email: "leo.ingram@example.com",
    workspaceId: 1,
    memberId: 29,
  },
  {
    id: 30,
    name: "Ava Johnson",
    nickname: "RoboticsPro99",
    position: "Robotics Engineer",
    status: "Available",
    profileImgUrl: "https://picsum.photos/100",
    isOnline: true,
    isOwner: false,
    createdAt: new Date("2025-06-25"),
    updatedAt: new Date("2025-06-25"),
    email: "ava.johnson@example.com",
    workspaceId: 1,
    memberId: 30,
  },
];
export default dummyProfiles;
